src/modules/mod.rs

Fixes small typo "symlining --> symlinking"

typo: symlinking

---

src/manifests/mod.rs

This change runs create_dir_all on the base directory of a file in the files module before attempting to write it.

ensure directories are created

---

src/main.rs

Swap `--manifest-directory` to a positional argument with no default. This will stop new users running `comtrya` and having their disk scanned for manifests.
`--debug` and `--trace` are also swapped out for `-v` and `-vv`.

chore: make Comtrya command safer by default

---

opt/get.comtrya.dev/ps.html

Powershell script for downloading `comtrya.exe` (msvc) latest version.
The binary will be downloaded into `$HOME\.comtrya` directory and the description text, once downloaded, explains how to add it to the Windows path from Powershell.
Signed-off-by: nunix <corsair@hey.com>

Added Powershell download script

---

src/actions/package/install.rs
src/actions/package/mod.rs

We add a little custom deserializer that can handle single strings or lists of strings.
That allows us to treat `name` and `list` from the YAML as a single field in Rust.

chore: add custom deserializer for name or list of packages

---

src/actions/file/copy.rs
src/actions/file/mod.rs

Previously, we'd attempt to render everything in the `files` directory
within a manifest. This doesn't work too well when the files contain
jinja style braces, such as bash/zsh configs, and fails terribly.
Now we only render individual files when enabled

fix: only render files which have templating enabled

---

src/actions/package/providers/yay.rs

Resolves #136
-Qq with package list is chosen for efficiency (no need to query each
package individually)
There is a bit sad edge case where you can request installation of
something like `pkg-config` but the package is actually called
`pkgconf` where this will fail to detect already installed. But the
"fix" is simply to add the proper package name :)
I don't see a way of solving this without shelling out for each
package individually or saving all the package aliases.

feat: implement already installed query for provider yay

---

Cargo.toml

I don't remember entirely why this was set to vendored, but I seem to recall it was when I added remote manifest support with Git. Sadly, #143 does seem to indicate this causes issues on BSD systems.
Let's try without and see what breaks

fix: removed vendored openssl

---

Cargo.toml

fix: attempt to remove openssl, as it's not a direct dependency

---

src/actions/package/providers/bsdpkg.rs
src/actions/package/providers/mod.rs

Successfully tested installing packages on FreeBSD without specifying the provider in the manifest. Default provider tested for dfly, too. It works but there's an issue with the actual package installation that I need to look into separately.

Add default package provider info for FreeBSD and DragonFly BSD

---

examples/Comtrya.yaml
src/actions/directory/copy.rs
src/actions/directory/mod.rs
src/actions/file/link.rs
src/config/mod.rs
src/contexts/mod.rs
src/contexts/variables.rs
src/main.rs

- variables are added via "Comtrya.yaml":
```yaml
variables:
fkbr: "sxoe"
kuci: "xhpv"
```
which yields
```bash
DEBUG context="variables" key="fkbr" value="sxoe"
DEBUG context="variables" key="kuci" value="xhpv"
```

[feat] variables context

---

src/contexts/env.rs
src/contexts/mod.rs

- reads environment variables and injects them into own context

[feat] add "env" context

---

src/main.rs

This is a problem because we attempt to "strip" the manifest directory as a prefix during some file.* operations and this fails when the path hasn't been resolved / canonicalized properly
Closes #146

fix: ensure we canonicalize manifest directory in-case it's a symlink

---

.gitignore
examples/git/clone.yaml
src/actions/git/clone.rs
src/actions/git/mod.rs
src/actions/mod.rs
src/atoms/git/clone.rs
src/atoms/git/mod.rs
src/atoms/mod.rs

feat: action and atoms for git.clone

---

src/actions/package/providers/dnf.rs
src/actions/package/providers/mod.rs

Hi, this is my first contribution to Comtrya - I think it's a great project and I use it for my own dotfiles management.
This pull request is to add DNF package manager support for Red-Hat based systems including Fedora, CentOS and RHEL. As a lot of users use Fedora or other Red-Hat based systems, I think its important that it's supported by Comtrya.
It is a **WIP**, I have added 5 TODOs in the non-test code that I would like a reviewer to check as I'm not sure of the best approach to them. Especially the use of the `query()` function, if the solution is to simply stick to using `package.packages()` then that is no problem and the commented out code can be removed.
Thanks for looking at my PR!
Unfortunately some of the detection for Fedora 35 from the dependency `os_info` is a bit off in …

[WIP] feat: Add support for DNF package manager for Red-Hat based distros

---

Cargo.toml
src/actions/package/install.rs
src/actions/package/mod.rs
src/actions/package/providers/aptitude.rs
src/actions/package/providers/bsdpkg.rs
src/actions/package/providers/dnf.rs
src/actions/package/providers/homebrew.rs
src/actions/package/providers/mod.rs
src/actions/package/providers/pkgin.rs
src/actions/package/providers/winget.rs
src/actions/package/providers/yay.rs
src/actions/package/repository.rs

This PR seperates `PackageRepository` from `PackageInstall`.
Which means that this:
```yaml
actions:
- action: package.install
name: something
repository: blah
```
Becomes:
```yaml
actions:
- action: package.repository
url: somewhere
key:
url: blah
name: blah
- action: package.install
name: something
```
Closes #172

feat: seperate package repository and install

---

lib/src/actions/package/providers/mod.rs
lib/src/actions/package/providers/xbps.rs

xbps package manager is used with void linux https://voidlinux.org/

Add support for XBPS package manager

---

app/src/commands/apply.rs
examples/where/main.yaml
lib/src/actions/file/link.rs
lib/src/contexts/mod.rs
lib/src/manifests/mod.rs
tests/basic_usage.rs

- use rhai scripts to use condition
- if the rhai script resolves to true -> run manifest
- if the rhai script fails or resolves to false -> don't run manifest
- context variables can be used
If a manifest runs or not depends on the `dry run` option. Manifest execution can be fine tuned by adding `where` conditions.

 [#196][feat] add where condition to manifests

---

lib/src/actions/package/providers/mod.rs
lib/src/actions/package/providers/zypper.rs

Current behavior, prior to code in PR, is no package support for Zypper.
Add support for Zypper on OpenSUSE and SUSE distributions. Allow the user to install packages with zypper through the use of comtrya.
Feature request that was noticed.
OpenSUSE tumbleweed
Version (`comtrya --version`): comtrya 0.7.4
OpenSUSE Tumbleweed

Zypper support

---

.github/workflows/main.yaml
.github/workflows/pull-request.yaml

- https://github.com/actions/virtual-environments/issues/5583
macOS build fails due to deprecation

[fix] macOS build (deprecation)

---

lib/src/atoms/file/link.rs

source path: `\\?\C:\Users\kecrily\Desktop\dev\per\dotfiles\modules\node\files\.npmrc`
link: `C:\Users\kecrily\Desktop\dev\per\dotfiles\modules\node\files\.npmrc`
So https://github.com/comtrya/comtrya/blob/c4705ca646c89912442ed9bd8e1564f7015c73ee/lib/src/atoms/file/link.rs#L59
will always be `true`.
A link action was executed before, and then an error occurs when it is executed again.
`source` is canonical.
Make the file.link action available on Windows.
Version (`comtrya --version`): comtrya 0.7.4
Operating system: Windows 11 Dev Preview

fix(windows): adjust to canonical source path

---

lib/src/actions/binary/github.rs
lib/src/contexts/env.rs
lib/src/contexts/mod.rs
lib/src/contexts/os.rs
lib/src/contexts/user.rs
lib/src/contexts/variable_include/mod.rs
lib/src/contexts/variables.rs
lib/src/lib.rs
lib/src/values/mod.rs

We use the `Value` struct from `serde_yaml` which is tied to their crate.
> nothing to say
We want to have an own implementation of a `Value` class which does not depend on any external crate.
Be more independent from outside development
> nothing to say

Context enum

---

lib/src/actions/package/providers/macports.rs
lib/src/actions/package/providers/mod.rs

No support for macports package manager.
Allow installing software with macports.
Feature request for MacPorts support as per issue #191 
Version (`comtrya --version`): comtrya 0.7.4
Operating system: Mac Os 
---
This is a feature request from @theowenyoung. Would like some input on this. Right now the implementation assume that macports is installed and it's binary is in $PATH. 
Would like to provide the bootstrap functionality in a separate PR, how that is handled can be talked about in the issue.
There are some clippy warnings regarding unused imports. I do intend to make use of these as I play around with the bootstrap process. I can remove them for this PR is needed.

Initial support for Macports

---

CONTRIBUTING.md

> installation instructions of `nextest` are wrong
> nothing to tell here
> nothing to tell here
> nothing to tell here
> nothing to tell here

[fix] documentation about installing nextest

---

lib/src/actions/file/mod.rs

- [ x] documentation addition
When a file is not found or file resolution fails due to some other error, the error message received is not very descriptive of what file caused the problem. See #198 for an example of the error. Closes #199 .
The error message should assist the user in solving the problem by displaying what path caused the issue and what manifest the file was pulled from.
To provide a better UX when/if something goes wrong.
Operating system: Windows 11, WSL2 running Ubuntu 20.04

refactor: add more descriptive error message to file resolution

---

app/src/commands/apply.rs
lib/src/actions/binary/github.rs
lib/src/actions/command/run.rs
lib/src/actions/directory/copy.rs
lib/src/actions/directory/create.rs
lib/src/actions/file/copy.rs
lib/src/actions/file/download.rs
lib/src/actions/file/link.rs
lib/src/actions/file/mod.rs
lib/src/actions/git/clone.rs
lib/src/actions/macos/default.rs
lib/src/actions/mod.rs
lib/src/actions/package/install.rs
lib/src/actions/package/repository.rs
lib/src/actions/user/add.rs

- [x ] feature
Currently, errors resulting from files not being found are not bubbled up and factored in to execution of steps
Missing files should be reported when necessary, and affect planning of steps
Better UX when files necessary for a step are missing or weren't created in a previous step
Operating system: Windows 11/WSL2 Ubuntu 20.04

Improve Plan Process

---

app/src/commands/apply.rs

Comtrya stops as soon as an action returns an empty plan, meaning no further actions run.

fix: ensure all actions in a manifest run

---

lib/src/actions/directory/copy.rs
lib/src/steps/initializers/command_found.rs

Directories fail to copy on windows
Run a directory copy manifest on windows
#275 
Be able to have a manifest copy a directory
Fix broken functionality
Version (`comtrya --version`): 0.8.0
Operating system: Windows 11

Windows directory copy

---

lib/src/actions/package/providers/winget.rs
lib/src/steps/initializers/command_found.rs

Issues outlined in #277 
Use winget to install software
Bug report in issues #277 
Version (`comtrya --version`): 0.8.0
Operating system: Windows 11

Modify flags during install run for Winget

---

app/src/commands/apply.rs

fix: ensure failed where clause doesn't stop exeuction

---

README.md

README.md includes several badges but none about packaging.
Include badge about packaging.
Keeping track of this form of adoption of Comtrya and showing potential users how they can install it other than from source or fetch script. (It's a bit weird, though, that the latest release on GH is reported to be 0.8.1 while on crates.io it's 0.8.2! Looks like it was only tagged but no release made?)

Add packaging status to readme

---

app/src/commands/apply.rs
examples/Comtrya.yaml
examples/group/add_to_group.yaml

The examples showed the `manifest_path` configuration incorrectly as `manifests`.
We also didn't support local dependency resolution. I know this shouldn't be the same PR, but I got carried away debugging.
Closes #278

fix: manifest_paths example and local dependencies

---

Cargo.lock
app/Cargo.toml
app/src/commands/apply.rs
app/src/commands/contexts.rs
app/src/commands/mod.rs
app/src/commands/version.rs
app/src/main.rs
lib/Cargo.toml
lib/src/atoms/file/copy.rs
lib/src/contexts/mod.rs

contexts command

---

Cargo.lock
examples/toml-examples/command/command.toml
lib/Cargo.toml
lib/src/manifests/load.rs

Comtrya only support manifest files written in yaml.
Comtrya will be able to support manifests written in toml
Request in #285 
Version (`comtrya --version`): 0.8.2
Operating system: Fedora 37

Initial implementation for supporting toml files

---

lib/src/actions/user/providers/macos.rs
lib/src/actions/user/providers/mod.rs

Adding users is not implemented on MacOS
Ability to add users to a MacOS system using comtrya
Feature parody with FreeBSD and Linux
Version (`comtrya --version`): 0.8.3
Operating system: MacOS 13.1

[Feature] Add users on MacOS Platform

---

lib/src/actions/group/providers/macos.rs
lib/src/actions/group/providers/mod.rs
lib/src/actions/user/providers/macos.rs

Group management is unimplemented
Ability to add groups and users to groups on MacOS systems.
Feature parity with other operating systems.
Version (`comtrya --version`): 0.8.3
Operating system: MacOs 13.1

Add users to group and add groups

---

README.md

fixes #309 
No explanation about version pinning

Explain version pinning feature

---

lib/src/contexts/user.rs

Adds data dir, local data dir, and document dir to possible contexts usages in templating.
Most notably Neovim uses Local Appdata on windows. This makes linking it easier than manually constructing the command.
Since I was there, I added data and documents so I thought those could be useful for some setups.

Add more possible dirs to template context

---

Cargo.lock
app/Cargo.toml
jsonschemagen/Cargo.toml
lib/Cargo.toml
lib/src/atoms/file/copy.rs

All dependency entries were sorted.
`eval`, `fs_extra`, and all dev dependencies were dropped from the `app` crate as they were unused. `eval`, `fs_extra`, `openssl`, `paw`, `structopt`, and`tracing-subscriber` were dropped from regular dependencies of the lib crate, and `tempdir`, `assert_cmd`, `predicates`, and `assert_fs` were removed from dev-dependencies. 
In one test, usage of `tempdir` was replaced with the tempdir functionality of `tempfile` as `tempdir` is deprecated.
Every dependency was bumped to the latest possible minor version. Major versions would likely require a more hand-done audit, but minor versions are *supposed* to be back-compatible and safe to update aggressively. Tests still run fine after doing this, so I'm erring on that semver was properly followed for …

Prune unused deps + general dependency cleanup

---

app/LICENSE
lib/LICENSE

Some methods of packaging have a preference for having the license file in the root of the project. Ravenports is an example. This should allow for adding license files property to port systems.
Version (`comtrya --version`): v.0.8.4

add license to crates for packaging

---

examples/onlyvariants/main.yaml

Change the example variant to remove rebooting on a linux variant.

change the example for linux so not to cause a system reboot

---

.github/workflows/main.yaml

- publish "comtrya-lib" before "comtrya"
- bump Ubuntu to 22.04

chore: don't use a dedicated action to publish comtrya

---

.github/workflows/main.yaml
.github/workflows/pull-request.yaml
.gitignore

Chore: noticed that some ubuntu runners were using 20.04 when 22.04 is available.

update ubuntu runners and update gitignore

---

.github/workflows/main.yaml
.github/workflows/pull-request.yaml
Cargo.lock
lib/Cargo.toml

Binaries for aarch64-unknown-linux-gnu are not compiled correctly in the artifacts.
aarch64-unknown-linux-gnu binary is an actual aarch64 binary

fix: attempt to fix aarch64 linux binaries

---

lib/src/manifests/load.rs

chore: enhance manifest loading

---

Cargo.lock
lib/Cargo.toml
lib/src/atoms/file/mod.rs
lib/src/atoms/file/unarchive.rs

Comtrya does not have anything to unarchive a compressed file
Add an atom that can be built upon to uncompress a tar ball.
Seems like something useful.
Version (`comtrya --version`): v0.8.7
Operating system: macOS 14.1

add unarchive atom

---

.github/workflows/main2.yaml
lib/Cargo.toml

Experimental wf targets

---

Cargo.lock
lib/src/actions/binary/github.rs
lib/src/atoms/file/unarchive.rs

- fix: cargo fix warning
- nit: Cargo.lock found one update

fix: octocrab::instance needs to be wrapped in a runtime call

---

.github/workflows/main2.yaml

Add some forgotten conversion from matrix.job to matrix.platform

---

examples/command/run.yaml
lib/src/actions/command/run.rs
lib/src/actions/mod.rs

Chore
Related to #318 
`sudo` won't always be how we elevate privileges, and the atoms we built actually allow for abstracted `privilege` elevation, not sudo. Our `command.execute` action was specifically expecting `sudo: true`.
This is an intermediate solution where we support both `sudo: true` and `privileged: true`, and in the future we may support alternative elevations (teleport, doas, ?)

chore: sudo should be called privileged in command.execute

---

lib/src/atoms/command/exec.rs

fix: correct error propagation from exec errors

---

lib/src/actions/mod.rs
lib/src/manifests/load.rs
lib/src/manifests/mod.rs

fix: error when there's unrecognized fields in manifest

---

docs/src/variants.md

- [ *] bug fix
- [ *] documentation addition
It's a small error.
```
actions:
- action: command.run
command: echo
args:
- hello, vanilla Linux!
variants:
- where: os.family == "unix"
command: echo Hi, Unix
- where: os.distribution == "Ubuntu"
command: echo Hi, Ubuntu
- where: os.bitness == "64-bit"
command: echo Hi, 64 bit!
```
```
DEBUG execute:{manifest="b"}:{action=command.run}: Atom failed to execute: No such file or directory (os error 2)
ERROR execute:{manifest="b"}: Failed
```
```
TRACE execute:{manifest="c"}:{action=command.run}: stdout: Hi, Unix
```
Version (`comtrya --version`): 0.8.8
Operating system: Linux

fix: vartiants examples

---

app/src/commands/apply.rs
lib/src/actions/file/copy.rs
lib/src/actions/mod.rs

- [ *] feature
Even run ``` -vv (tracing mode),``` didn't provide action key information.
For example CopyFile, can't figure out about source and destination.
```
TRACE load_config{args=GlobalArgs { manifest_directory: None, no_color: false, verbose: 2, command: Apply(Apply { manifests: [], dry_run: false, label: None }) }}:load_config: No Comtrya.yaml found in current working directory
TRACE load_config{args=GlobalArgs { manifest_directory: None, no_color: false, verbose: 2, command: Apply(Apply { manifests: [], dry_run: false, label: None }) }}:load_config: No Comtrya.yaml found in users config directory
TRACE build_contexts: context="user" key="id" value="1000"
...
TRACE build_contexts: context="env" key="MANAGERPID" value="116167"
TRACE execute: manifests=""
...
TRACE execute: Add …
```

Add action summary information. (#254)

---

.github/workflows/pull-request.yaml

Taurplin fails because min rust verison is 1.70 in pull-request.yaml
CI pipeline runs for pull-request.yaml

update min rust version

---

Cargo.lock
app/Cargo.toml
app/src/main.rs

directly output log to stdout.
It's not a bug, more like a log enhancement with journalctl. #254 
Once, tracing_journald supported.
```
journalctl -f  F_MANIFEST=zellij -o json-pretty
{
"CODE_LINE" : "268",
...
"SYSLOG_IDENTIFIER" : "comtrya",
"_COMM" : "comtrya",
"F_MANIFEST" : "zellij",
"SPAN_TARGET" : "comtrya::commands::apply",
"TARGET" : "comtrya::commands::apply",
...
}
```
```
journalctl -t comtrya                       ### all comtrya log
journalctl -t comtrya F_MANIFEST=zellij     ### comtrya manifest zellij log       
```
Linux users can easy trace manifests actions by journalctl.
Version (`comtrya --version`): 0.8.8
Operating system: Fedora

add tracing_journald support for linux

---

Cargo.lock
app/Cargo.toml
app/src/commands/apply.rs
app/src/commands/contexts.rs
app/src/commands/version.rs
app/src/config/mod.rs
app/src/main.rs

As https://github.com/TeXitoi/structopt mention clap already support derive and structopt would not add new features.
Switch to clap, clean some dependency.

refactor: replace structopt/paw with clap

---

lib/src/actions/package/providers/aptitude.rs

`sharekeyrings` -> `share/keyrings`
- [*] bug fix

fix(aptitude): missing `/` for `share/keyrings`

---

lib/src/actions/package/providers/bsdpkg.rs

bsdpkg provider fails to install.
Run the following manifest snippet on a FreeBSD system
```
actions:
- action: package.install
list:
- sd
- just
```
Should install successfully
Refer to issue #433 
We pass in the `-n` option when it should be `-y` so that way comtrya can automatically pass in the yes option when prompted with the 'are you sure' prompt from the package manager.
Version (`comtrya --version`): 0.8.8
Operating system: FreeBSD 14.1

correct install option

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Add sections in issue templates to ask for manifest examples.

Add asking for manifests in the issue templates

---

.github/workflows/main.yaml
.github/workflows/pull-request.yaml

Current linux runners use 22.04. 24.04 is now available.
Linux test runners will run on 24.04
Version (`comtrya --version`):v0.8.8
Operating system:N/A

More ci updates

---

.github/workflows/mdbook-pr.yml

We don't validate that mdbook documentation is not broken on a PR.
Compile the mdbook on PR to make sure that changes to it in a PR do not break it.
See issue #446 
Version (`comtrya --version`): N/A
Operating system: N/A

Add workflow to compile mdbook on pull request

---

lib/src/atoms/file/link.rs
lib/src/config/mod.rs

Some errors were being logged as debug and not as an error.
Errors should be logged as errors.
See issue #247 
Operating system: macOS 14.5

Change some trace to warn message and some debug to error messages

---

lib/src/actions/user/add.rs

Action `user.add` fails if the user already exists.
```yaml
actions:
- action: user.add
fullname: Test User
home_dir: /home/test
username: test
shell: /bin/sh
```
Pass without fail if user already exists.
Should not be marked as a failing result.
Version (`comtrya --version`): ccdf5e1
Operating system: FreeBSD 14

Detect if users already exists instead of failing. Fixes #431

---

docs/src/packages.md
lib/src/actions/package/install.rs
lib/src/actions/package/mod.rs
lib/src/actions/package/providers/bsdpkg.rs
lib/src/actions/package/providers/zypper.rs

Package providers are not able to utilize local package files (such as `.deb` for apt and `.pkg` for FreeBSD's pkg) with a system's package manager.
Not a bug.
For this PR. Just to implement the first package provider, FreeBSD's pkg, with this feature.
Here is a sample manifest:
```
actions:
- action: package.install
name: ./examples/test/nano-8.1.pkg
file: true    
```
As of this PR, true will be required. I will create an issue for creating the ability to detect if its a file versus not a file.
See issue #430 
Version (`comtrya --version`): v.0.8.9
Operating system: FreeBSD 14.1

intial code for feature for local package installs

---

lib/src/actions/package/providers/aptitude.rs

Check that `share/keyrings` is correct.
No regression test for #434 
To have a regression test to catch this kind of issue with a string literal
Requested in issue #435 
Operating system: macOS 14.6.1

Add a regression test for issue #434

---

docs/src/cli.md
docs/src/commands.md

No documentation or mention exists in the documentation.
Some documentation for feature in docs.
#423 
Operating system: macOS 14.6.1

Add documentation for status command

---

docs/src/packages.md
lib/src/actions/package/install.rs

Aptitude can not use local files for install.
Can use local files for install. These are `.deb` packages.
#430 
Operating system: Debian 12

Enable aptitude for local file install

---

lib/src/actions/command/run.rs
lib/src/actions/directory/copy.rs
lib/src/actions/directory/create.rs
lib/src/actions/directory/remove.rs
lib/src/actions/file/copy.rs
lib/src/actions/file/download.rs
lib/src/actions/file/link.rs
lib/src/actions/file/remove.rs
lib/src/actions/group/add.rs
lib/src/actions/package/install.rs
lib/src/actions/package/repository.rs

Actions don't implement a summarize.
Provide a summarize summary for actions
Operating system: macOS 14.6.1

add summarize implementations to actions

---

docs/src/files-and-directories.md
lib/src/actions/file/copy.rs

File copy fails when `to` is a directory.
```
actions:
- action: file.copy
from: sample.txt
to: /tmp/
```
This action to pass with comtrya appending the file name to the target
#315 
Operating system: macOS 14.6.1

Append file name to target if target is a directory

---

lib/src/actions/directory/copy.rs

`directory.copy` always copies the entire directory.
With this PR, if I specify:
```yaml
actions:
- action: directory.copy
from: /tmp/a
to: /tmp/b/
```
then the directory  `/tmp/b/a` will not exist, but all the contents of `/tmp/a` will be in `/tmp/b/...`
After running the above manifest:
```sh
$ find /tmp/a
/tmp/a/.hidden.txt
/tmp/a/doc.txt
$ find /tmp/b
/tmp/b/.hidden.txt
/tmp/b/doc.txt
```
Users should be able to copy only the contents of a directory, and not the directory itself.
Version (`comtrya --version`): comtrya 0.8.9
Operating system: FreeBSD 14

Copy directory contents if target ends with a trailing slash (/)

---

.github/workflows/mdbook.yml

- [] feature
The deploy mdbook workflow fails in my fork because I don't have permission to publish.
It would be great to see that all tests pass / fail when looking at my fork commit history without having to account for the deploy workflow always failing.

Deploy mdbook only if owner is comtrya.

---

app/src/commands/apply.rs

When a lists of manifests name are passed in using the `-m` option, they are not checked to see if they are paths.
Using the samples in the repos `examples`, run the following
```shell
comtrya apply -m examples/command/run
```
With how has been, it is easy to assume the above is valid, when it is not.
Fail with output suggesting that names, not paths are expected.
Also, addition information in the apply options help dialog.
#470 
Operating system: macOS 15

Add a check over supplied manifests for paths

---

lib/src/actions/group/providers/freebsd.rs
lib/src/actions/user/providers/freebsd.rs

Unable to run `cargo test` due to compiler errors.
Run `cargo test` on FreeBSD.
Should see testing output.
Version (`comtrya --version`): 73b462d
Operating system: FreeBSD 14

Fix tests for user and group providers on FreeBSD.

---

docs/src/files-and-directories.md

As discussed in #474 I added a note to the file command documentation to explain the need for the "files" directory. 
Note: There is also discussion on changing the behaviour here: #96 
@rawkode @martintc Please tell me if you expected it in a different way as you probably know best how you wanted to structure your documentation

Add documentation for file command behaviour

---

lib/src/atoms/command/exec.rs
lib/src/contexts/privilege.rs

Comtrya only supports sudo and doas as privilege providers.
run0 for systemd should also be supported.
issue #451 
Operating system: Arch Linux

Add run0 as a privilege provider

---

docs/src/packages.md

Add snapcraft to the list of package managers in the documentation

---

README.md
docs/src/installation.md

The documentation has an person passing in VERSION as an environment variable for pinning a specific version of comtrya correctly.
#494 
A person can use the curl and piped to bash script to get a specific version of comtrya.
#494

fix documentation

---

docs/src/packages.md
lib/src/actions/package/providers/mod.rs
lib/src/actions/package/providers/paru.rs

Comtrya does not have a provider for [Paru](https://github.com/Morganamilo/paru)
Not a bug
Addition of Paru to the list of available providers
Paru is my preferred AUR helper and I'm sure others would want the option to use Paru over Yay
Version (`comtrya --version`): comtrya 0.9.0
Operating system: Arch

feat: add paru as new providor

---

lib/src/actions/package/providers/yay.rs

fix(arch): no diffmenu is now the default and the flag was removed

---

docs/src/files-and-directories.md

Document behavior of the `file.chown` action

doc: document file chown action

---

examples/file/file-download-chown.yaml
lib/src/actions/file/download.rs
lib/src/atoms/file/chown.rs

Comtrya does not currently have the ability to run a chown in conjunction with a `file.download` action.
Optional ability to have a chown run on a `file.download` action if an user owner and user group is specified on unix systems.
issue #500 
Version (`comtrya --version`): main
Operating system: macOS 15.1

feat: chown files on download

---

docs/src/files-and-directories.md

Document the use of chown during file download. Also, add more to the note on the chown action.
Version (`comtrya --version`): main
Operating system: macOS 15.1

doc: chown on file download

---

docs/src/files-and-directories.md
lib/src/actions/file/copy.rs

Files can be copied, but chown must take place in a separate action.
Can provide options for chown to run within a single action of file copy.
#500 
Version (`comtrya --version`): main
Operating system: macOS 15.1

add chown options to file.copy action

---

examples/file/file-unarchive.yaml
lib/src/actions/file/mod.rs
lib/src/actions/file/unarchive.rs
lib/src/actions/mod.rs

Comtrya is not able to unarchive files
Provide an action that can unarchive .tar.gz files
#231 
Version (`comtrya --version`): v0.9.0
Operating system: macOS 15.1.1

feat: add unarchive file action

---

lib/src/actions/binary/github.rs

Action was throwing error due to no summary for me.
Not to throw errors due to lack or summarization.
Version (`comtrya --version`): v0.9.0
Operating system: macOS 15.1.1

add summary for action

---

app/src/config/mod.rs
docs/src/cli.md

cli option -c provides users the option to specify a specific configuration file path
N/A
N/A
Adding documentation
Version (`comtrya --version`): comtrya 0.9.0
Operating system: MacOS

doc: Document new cli option for specifying configuration path

---

lib/src/manifests/load.rs

Files placed within `files` only get ignored as manifests if they are within the top level of `files`, the walker otherwise descends in to subdirectories and searches for manifests.
1. Create a `files` folder for a manifest to source from
2. Create another folder within `files`, ie `files/foo`
3. Create a `.yml` or `.toml` file within the subfolder, ie `files/foo/some_config.yml`
4. Comtrya picks up this file as a manifest, and attempts to run it.
`files` does not get descended into at all, so that yaml and toml based configs work as expected if they aren't at the top level of `files`
Bitten by this on `.cargo/config.toml` and `.config/jj/config.toml`
This fixes it by filtering out `files` directories at the walker build step, preventing it from being descended into at all.
Ideal UX flow …

fix: purge "files" at the ignore walker phase instead of the final walk

---

lib/src/manifests/providers/git.rs
lib/src/manifests/providers/mod.rs

As of version v0.8.9, Comtrya is no longer able to pull manifests from git sources. This re-introduces it with utilizing gix to resolve issues we had with GitSync and git2-rs with openssl.
```shell
comtrya -d https://github.com/martintc/test-dotfiles apply
```
Can fetch and clone a git repo containing comtrya manifests and apply them.
#511 
That may not be a 100% replacement of older functionality, but I want something out there and that can be tested.
It will not rebase or pull changes after it a repo has been pulled. This is a future update. For now, if you update your repo and need to pull those changes, you can remove the repo that is clones from the "cache_dir" where comtrya places them. 
[This](https://docs.rs/dirs-next/2.0.0/dirs_next/fn.cache_dir.html) is a link to the dirt-next …

feat: gix manifest sourcing

---

lib/src/manifests/load.rs

Having YAML and TOML config files for other applications in subdirectories in the `files` directory, those are tried to be parsed by comtrya, resulting in a parsing error.
Just place any YAML or TOML file in the `files` directory and e.g. run `comtrya status`. Comtrya tries to parse not only manifest files but also the files within this directory.
Comtrya should ignore everything within the `files` directory while loading the manifests, as stated in the documentation.
To make it works as expected.
Version (`comtrya --version`): 0.9.1
Operating system: macOS 15.1.1
Description:
This fixes ignoring the 'files' directory during walker ignore phase by fixing the check condition to actually check for a directory instead of a file.
Also improves the whole check by:
- using DirEntry::file_type() …

fix: properly ignore files directory

---

lib/src/actions/user/add.rs
lib/src/actions/user/add_group.rs

Output shows that the summarize functions are not implemented for user actions.
In the tracing output have a proper summary for user actions.
Version (`comtrya --version`): 0.9.1
Operating system: macOS 15.2

implement summarize for user actions

---

lib/src/actions/binary/github.rs

This change pertains to when a github binary is being downloaded using comtrya. When the value of the version is **latest**,  it treats the version as the literal version rather than the logical meaning of it.
This issue is further described in the bug - https://github.com/comtrya/comtrya/issues/535 
1. Create a yaml file (**Comtrya.yaml**) with the following code - 
```
actions:
- action: binary.github
name: bat
directory: /Users/sreerag-n/codes/github/comtrya/examples/binary
repository: sharkdp/bat
version: latest
```
2. Run the command to download the binary
```
comtrya apply
```
3. It will fail saying that it failed to find a release.
When the version value passed is **latest**, it should fetch the latest version of the binary.
This fix addresses the bug raised in …

fix(binary.github): added code to fetch the latest binary when version value passed is 'latest'
