src/actions/file/link.rs, src/actions/file/mod.rs, src/actions/mod.rs, src/main.rs
=> feat: file.link action added

src/actions/file/link.rs, src/main.rs
=> fix: check if the symlink exists to the correct file before linking

.github/release-notes-configuration.json, .github/workflows/release.yml
Please note: I have no idea what I'm doing and I just read the docs at https://github.com/mikepenz/release-changelog-builder-action#configuration. I have no idea if this works.
=> Add uncategorised PRs to release notes

src/actions/package/providers/mod.rs, src/actions/package/providers/winget.rs
=> feat: support Winget for Windows

src/actions/file/copy.rs
=> feat: support chmod / permissions for file.copy

README.md, src/actions/command/run.rs, src/actions/package/providers/aptitude.rs, src/actions/package/providers/mod.rs, src/actions/package/providers/yay.rs, src/utils/command.rs
Hey! Very cool project! :smile:
Was setting up an old laptop at home and came across this very promising project. My wife and I are using Arch/Manjaro and having support to yay/pacman would be great!
=> feat: Add yay provider

src/actions/command/run.rs, src/actions/directory/copy.rs, src/actions/directory/mod.rs, src/actions/file/copy.rs, src/actions/file/link.rs, src/actions/file/mod.rs, src/actions/mod.rs, src/actions/package/install.rs, src/actions/package/mod.rs, src/actions/package/providers/mod.rs, src/main.rs
=> feat: "--dry-run" flag

Cargo.lock, Cargo.toml, README.md, src/actions/directory/copy.rs, src/actions/mod.rs, src/main.rs, tests/README.md, tests/basic_usage.rs, tests/utils.rs
Shows a very early structure for integration tests
=> feat: end to end tests and initial ChangeSets

examples/command/run.yaml
Been sitting on this one waiting for the last merge :P
Dunno if you wanna encourage this kind of usage, but it was very useful for me when I worked it out.
=> Add example of a more complex command construction

src/main.rs
=> feat: add ability to print version

README.md
updated Usage to include version print.
=> update to include version print

src/contexts/mod.rs, src/contexts/os.rs
Co-authored-by: sid.palas@gmail.com
=> feat: add OS contexts

examples/directory/create.yaml, src/actions/directory/create.rs, src/actions/directory/mod.rs, src/actions/file/copy.rs, src/actions/file/link.rs, src/actions/mod.rs
=> feat: directory.create action

examples/file/file-download.yaml, src/actions/file/download.rs, src/actions/file/mod.rs, src/actions/mod.rs, src/atoms/http/download.rs
=> feat: file.download action

examples/macos/defaults.yaml, src/actions/macos/default.rs, src/actions/macos/mod.rs, src/actions/mod.rs
=> feat: prototype macOS default support

README.md
Signed-off-by: Mario Constanti <mario@constanti.de>
=> fix broken release link

Cargo.toml, src/actions/mod.rs, src/contexts/mod.rs
We're preferring Rhai because it's expression only, rather than a complete scripting language.
Closes #163
=> feat: replace Koto with Rhai

.github/workflows/main.yaml
=> [ci] make tarpaulin run for the workspace

CONTRIBUTING.md
Help people starting with the `comtrya` contribution.
=> [doc] guides

docs/pull_request_template.md
> Don't use the PR template here, as I extend the PR template :D
=> [doc] extend PR template

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
It's nice to guide the user through the creation process of new issues.
=> [doc] add issue templates for bugs / feature requests

app/Cargo.toml, app/src/main.rs, lib/src/config/mod.rs
=> [feat] check for updates

app/src/commands/apply.rs, examples/labels/label.yaml, lib/src/actions/file/link.rs, lib/src/manifests/mod.rs
=> feat: allow label selector on manifest apply

lib/src/actions/package/providers/homebrew.rs, lib/src/manifests/mod.rs, lib/src/manifests/providers/git.rs, lib/src/tera_functions/mod.rs
=> Fix tera functions bug

lib/src/manifests/load.rs, lib/src/steps/initializers/command_found.rs
Everything to work as it did before.
Clean up the use of unwraps in the `lib/src/manifests/load.rs` file.
Version (`comtrya --version`): 0.8.0
Operating system: Fedora 37
=> Remove use of unwraps

lib/src/atoms/file/copy.rs
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/comtrya/comtrya/pull/294).
* #295
* __->__ #294
fix: check to location for file.copy
=> fix: check to location for file.copy

Cargo.lock, app/Cargo.toml, lib/Cargo.toml
=> release: v0.8.4

.github/workflows/main.yaml, .github/workflows/pull-request.yaml
=> bump minimum rust version

CONTRIBUTING.md
=> fix: broken link

.github/workflows/pull-request.yaml
=> update windows runner to 2022

.github/workflows/main.yaml, .github/workflows/pull-request.yaml, Cargo.lock, lib/Cargo.toml
This reverts commit 2fa4278b0b0ec8e9345f8e423643bb3372ed81b9.
=> Revert "fix: attempt to fix aarch64 linux binaries (#357)"

.github/workflows/main.yaml, .github/workflows/pull-request.yaml, lib/Cargo.toml
=> fix: aarch64 binary artifact

.github/workflows/main.yaml, .github/workflows/pull-request.yaml, lib/Cargo.toml
=> Fix aarch64 binary 2

.github/workflows/main2.yaml
=> Gh experiment wf

lib/Cargo.toml
=> vendor openssl

.github/workflows/main2.yaml
=> Correct more the environment variables for main2.yaml

.github/workflows/main2.yaml
=> remove renaming binary

.github/workflows/main2.yaml
=> experiment with naming parameters

.github/workflows/main2.yaml
=> Experimental yaml2

.github/workflows/main2.yaml
=> adjust bin name env variable

.github/workflows/main2.yaml
=> adjust targets

Cargo.lock, README.md, app/Cargo.toml, lib/Cargo.toml
=> prepare release

README.md
Add some instructions to the `README.md` on how to utilize the mdbook documentation.
=> add instructions for mdbook docs

docs/src/SUMMARY.md, docs/src/installation.md, docs/src/privileged.md
Add documentation to the mdbook based on pr #390 
=> Add documentation for privilege escalation.

.github/workflows/main.yaml, .github/workflows/pull-request.yaml
=> bump min rust version

Cargo.lock, app/src/main.rs, app/tests/utils/mod.rs, lib/Cargo.toml, lib/src/actions/directory/copy.rs, lib/src/actions/directory/create.rs, lib/src/actions/directory/remove.rs, lib/src/actions/file/copy.rs, lib/src/actions/file/download.rs, lib/src/actions/file/link.rs, lib/src/actions/file/remove.rs, lib/src/actions/group/providers/freebsd.rs, lib/src/actions/mod.rs, lib/src/actions/package/install.rs, lib/src/config/mod.rs, lib/src/contexts/variable_include/file.rs, lib/src/manifests/load.rs
- sidequest: fixed some clippy warnings
Closes #411.
=> refactor: replace deprecated serde_yaml with serde_yml

app/src/commands/contexts.rs, app/src/main.rs, docs/src/SUMMARY.md, docs/src/commands.md
Add come documentation for commands. Mostly for the contexts command.
Also removed the beta warning about it in the CLI output.
=> Document contexts

Cargo.lock, README.md, app/Cargo.toml, lib/Cargo.toml
=> prep for v0.8.9 release

.github/workflows/mdbook.yml
=> adjust dependencies of actions

.github/workflows/mdbook.yml
=> another shot at fixing mdbook deploy

docs/src/cli.md, docs/src/commands.md
N/A
N/A
Issue #470 
Update documentation to make it more clear on ways to run manifests in comtrya. More specifically, the usage of the `-d` and `-m` flags.
Operating system: macOS 15.0
=> update documentation for using apply

docs/src/command.md, docs/src/privileged.md
Documentation is needed for the new features in PR #479 and #481 
=> documentation on privilege escalation providers

.github/workflows/main.yaml, .github/workflows/pull-request.yaml
=> update to new runners for macos x86_64

docs/src/command.md
=> doc: add documentation for scoped environment variables

docs/src/files-and-directories.md
=> doc: file unarchive action

Cargo.lock, examples/git/clone.yaml, lib/Cargo.toml, lib/src/actions/git/clone.rs, lib/src/actions/git/mod.rs, lib/src/actions/mod.rs, lib/src/atoms/git/clone.rs, lib/src/atoms/git/mod.rs, lib/src/atoms/mod.rs
A few versions ago, dropped support for git because of issues with openssl.
This does not totally replace the original behavior of also using git to a manifest source, however I plan to follow up up with that if this proves to be successful.
I would appreciate people are able to and willing to, build this branch locally on your machine and just testing the `git.clone` action and reporting back if it works and one what platform you are on. If it does not, please report what platform and whatever messages are output.
See the following:
#511 
#439 
Version (`comtrya --version`): main
Operating system: macOS 15.1.1
=> feat: git clone via gix

docs/src/git.md
=> doc: document new git.clone implementation

docs/src/actions.md
=> doc: update foot note on git action

.github/workflows/main.yaml, .github/workflows/pull-request.yaml
=> ci: remove tarpaulin
